name: "backport-action"
description: "Automatically backport pull requests"
author: "zeebe-io"
inputs:
  github_token:
    description: Token for the GitHub API
    required: true
  github_workspace:
    description: The GitHub workspace directory path
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
