name: "backport-action"
description: "Automatically backport pull requests"
author: "zeebe-io"
inputs:
  github_token:
    description: Token for the GitHub API
    required: true
  github_workspace:
    description: The GitHub workspace directory path
    required: true
  version:
    description: The version of backport-action
    required: true
  label_pattern:
    description: A regex pattern to match the backport labels
    required: false
    default: ^backport ([^ ]+)$
runs:
  using: "node12"
  main: "dist/index.js"
